# Generated by Django 5.1.1 on 2024-11-17 13:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(default=uuid.UUID('195c6f34-2dcf-45b8-98cd-1d6e25bd8694'), max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_image', models.ImageField(upload_to='link_images/')),
                ('link_url', models.URLField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app.userprofile')),
            ],
        ),
    ]
